baseURL = "https://ryojifujishita.github.io/Ryoji-Fujishita-works/"
title = "Ryoji Fujishita Works"
theme = "PaperMod"
publishDir = "docs"

[pagination]
pagerSize = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Ryoji Fujishita Works"
description = "My portfolio website"
keywords = ["Portfolio", "Blog"]
author = "Ryoji Fujishita"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

[params.homeInfoParams]
Title = "Welcome to my portfolio 👋"
Content = "This is my personal website where I share my work and thoughts."

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20 