baseURL = "http://localhost:1313/"
languageCode = "ja"
title = "My Portfolio"
theme = "hugo-blox-builder"

[params]
  # サイトの設定
  description = "My Portfolio Site"
  author = "Your Name"
  email = "your.email@example.com"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[module]
  [[module.mounts]]
    source = "static"
    target = "static" 